#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the human steps of the milestone-one hand run (#11).
#
# The research job needs two keys in a gitignored .env, and the OpenRouter key
# needs a monthly limit of its own: the second of the two spend layers, so a
# bug in the per-run cap (spendCapUsd in research.config.yaml) cannot cost
# more than that ceiling. Re-running is safe: saved values are offered back.
#
#   bash scripts/hand-run-setup.sh
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

# Weekly runs at the 5 USD per-run cap could legitimately spend 52/12 * 5 ≈ 22 USD a month, so a
# ceiling below that would cut honest runs short. 25 USD leaves that room and still bounds a bug.
SUGGESTED_MONTHLY_LIMIT_USD=25

banner "KC Events: hand-run setup"

# ── Stage 1: OpenRouter key ────────────────────────────────────────────────
stage "OpenRouter: API key"
say "The research job pays for its model calls through one OpenRouter key."
open_url "https://openrouter.ai/settings/keys"
step "Sign in if asked, then click 'Create API Key' (or reuse the key you made for this job)."
step "Name it something you will recognize in the dashboard, e.g. kc-events."
step "Leave the credit limit for the next stage, or set it now if the form offers one."
step "Copy the key: OpenRouter shows it once, right after creating it."
ask_secret OPENROUTER_API_KEY "Paste the OpenRouter key:"
if [[ -z "${OPENROUTER_API_KEY:-}" ]]; then
  warn "no key given; the research job cannot run without one"
else
  write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
fi

# ── Stage 2: monthly limit on that key ─────────────────────────────────────
stage "OpenRouter: monthly limit on the key"
say "This is the second spend layer. The first, spendCapUsd in research.config.yaml, stops model"
say "calls inside a run; this one lives on the key itself, so a bug in the first cannot spend past it."
say "Suggested ceiling: ${SUGGESTED_MONTHLY_LIMIT_USD} USD a month (weekly runs at the 5 USD cap come to about 22)."
open_url "https://openrouter.ai/settings/keys"
step "Find the kc-events key in the list and open its edit menu."
step "Set its credit limit to ${SUGGESTED_MONTHLY_LIMIT_USD} (USD), and set the limit to reset monthly."
note "OpenRouter's key API calls these 'limit' and 'limit_reset' (daily / weekly / monthly). If the"
note "dashboard offers a credit limit but no reset period, set the limit anyway: it then caps the key's"
note "lifetime spend, which still bounds a bug; raise it by hand when it runs down."
step "Save the key."
pause "Press Enter once the limit is saved, and this wizard will read it back from OpenRouter."
if [[ -n "${OPENROUTER_API_KEY:-}" ]] && command -v curl >/dev/null 2>&1; then
  KEY_INFO=$(curl -sS --max-time 15 https://openrouter.ai/api/v1/key -H "Authorization: Bearer ${OPENROUTER_API_KEY}" 2>/dev/null || true)
  if [[ -z "$KEY_INFO" ]]; then
    warn "could not reach OpenRouter to read the key back; check the limit in the dashboard"
    SKIPPED+=("confirm the OpenRouter key's monthly limit in the dashboard")
  else
    say "OpenRouter reports for this key:"
    if command -v jq >/dev/null 2>&1; then
      printf '%s' "$KEY_INFO" | jq -r '.data | "    label: \(.label // "?")\n    limit: \(.limit // "none") USD\n    limit resets: \(.limit_reset // "never")\n    used so far: \(.usage // 0) USD"' 2>/dev/null || printf '    %s\n' "$KEY_INFO"
    else
      printf '    %s\n' "$KEY_INFO"
      note "(install jq for a tidier readout)"
    fi
    if command -v jq >/dev/null 2>&1; then
      KEY_LIMIT=$(printf '%s' "$KEY_INFO" | jq -r '.data.limit // "null"' 2>/dev/null || echo "?")
      KEY_RESET=$(printf '%s' "$KEY_INFO" | jq -r '.data.limit_reset // "null"' 2>/dev/null || echo "?")
    else
      KEY_LIMIT=$(printf '%s' "$KEY_INFO" | grep -oE '"limit"[[:space:]]*:[[:space:]]*[^,}]+' | head -n1 | sed -E 's/.*:[[:space:]]*//; s/"//g')
      KEY_RESET=$(printf '%s' "$KEY_INFO" | grep -oE '"limit_reset"[[:space:]]*:[[:space:]]*[^,}]+' | head -n1 | sed -E 's/.*:[[:space:]]*//; s/"//g')
    fi
    if [[ -z "$KEY_LIMIT" || "$KEY_LIMIT" == "null" ]]; then
      warn "the key has no limit yet"
      SKIPPED+=("set the monthly limit on the OpenRouter key (it reads back as none)")
    elif [[ "$KEY_RESET" != "monthly" ]]; then
      warn "the key has a limit but it does not reset monthly; it caps lifetime spend instead"
      SKIPPED+=("make the OpenRouter key's limit reset monthly, or remember to raise it when it runs down")
    fi
    confirm "Does the limit above look right?" || SKIPPED+=("fix the OpenRouter key limit in the dashboard")
  fi
else
  SKIPPED+=("confirm the OpenRouter key's monthly limit in the dashboard")
fi

# ── Stage 3: Tavily key ───────────────────────────────────────────────────
stage "Tavily: API key"
say "The discovery lane searches with Tavily. Basic searches cost one credit each; the free tier's"
say "1,000 credits a month cover the job's few dozen searches a week."
open_url "https://app.tavily.com/home"
step "Sign in, then find the API keys section on the home page."
step "Copy the default key, or create one named kc-events."
ask_secret TAVILY_API_KEY "Paste the Tavily key:"
if [[ -z "${TAVILY_API_KEY:-}" ]]; then
  warn "no key given; run with --no-discovery until there is one"
else
  write_env TAVILY_API_KEY "$TAVILY_API_KEY"
fi
# ──────────────────────────────────────────────────────────────────────────

finish
say "Next: the hand run itself, then grading."
say "  pnpm research          # 3-week horizon and 5 USD cap come from research.config.yaml"
say "  pnpm grade             # fills counts three and four of docs/milestone-one-grading.md"
printf '\n'
