#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the human steps that move the weekly run to this machine (#22, ADR 0010).
#
# The weekly run (scripts/weekly-run.sh) needs a clone of its own, the two keys in that clone's
# gitignored .env, a git credential that can push to main, and a cron line that can find pnpm. This
# wizard sets up each from the checkout it is run in. Re-running is safe: the clone is reused, keys
# are offered back, and the cron line is replaced.
#
#   bash scripts/home-run-setup.sh
#
# The GitHub workflow stays as the manual fallback; scripts/weekly-workflow-setup.sh sets its secrets.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
DEFAULT_RUN_DIR="$HOME/kc-this-week-run"
CRON_SCHEDULE="17 6 * * 1" # Mondays 6:17 a.m. local: early in the week, off the top of the hour

# bare VALUE prints VALUE without a trailing CR or one pair of surrounding quotes. The CLI reads .env
# with Node's loader, which drops both, but the library's re-run default is the raw line.
bare() {
  local v="${1%$'\r'}"
  if [[ "$v" =~ ^\"(.*)\"$ || "$v" =~ ^\'(.*)\'$ ]]; then v="${BASH_REMATCH[1]}"; fi
  printf '%s' "$v"
}

banner "KC This Week: home run setup"

# ── Stage 1: tools ─────────────────────────────────────────────────────────
stage "Tools: node, pnpm, git, flock, and gh signed in"
missing=()
for tool in node pnpm git flock gh; do
  command -v "$tool" >/dev/null 2>&1 || missing+=("$tool")
done
if (( ${#missing[@]} )); then
  warn "not on PATH: ${missing[*]}"
  step "Install them, then re-run this wizard."
  exit 1
fi
until gh auth status >/dev/null 2>&1; do
  warn "gh is not signed in"
  step "In another terminal, run: gh auth login"
  pause "Press Enter once gh auth status succeeds."
done
REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
# cron's PATH is nearly empty, so the cron line names where pnpm and node live on this machine.
CRON_PATH="$(dirname "$(command -v pnpm)"):$(dirname "$(command -v node)"):/usr/local/bin:/usr/bin:/bin"
say "The run will push to ${BOLD}${REPO}${RESET} as $(gh api user --jq .login)."
say "pnpm is $(command -v pnpm) and node is $(command -v node); the cron line will carry both."
confirm "Is that the right repo and account?" || { warn "run this from a clone of the right repo, signed in as the right account"; exit 1; }

# ── Stage 2: the dedicated clone ───────────────────────────────────────────
stage "A clone dedicated to the job"
say "The run commits to main from a clone of its own, so this checkout can be mid-work on any branch."
ask RUN_DIR "Clone path [${DEFAULT_RUN_DIR}]:"
RUN_DIR="${RUN_DIR:-$DEFAULT_RUN_DIR}"
RUN_DIR="${RUN_DIR/#\~/$HOME}"
if [[ -d "$RUN_DIR/.git" ]]; then
  say "Reusing the clone at $RUN_DIR."
else
  note "cloning $REPO into $RUN_DIR..."
  gh repo clone "$REPO" "$RUN_DIR" -- --quiet
fi
(cd "$RUN_DIR" && git switch --quiet main && git pull --quiet --ff-only origin main && pnpm install --frozen-lockfile --silent)
say "The clone is on main with its dependencies installed."
if [[ -z "$(cd "$RUN_DIR" && git config user.name)" || -z "$(cd "$RUN_DIR" && git config user.email)" ]]; then
  say "Git has no name and email here; the weekly commits need one."
  ask GIT_NAME "Name for the commits:"
  ask GIT_EMAIL "Email for the commits:"
  (cd "$RUN_DIR" && git config user.name "$GIT_NAME" && git config user.email "$GIT_EMAIL")
fi
say "Commits will be by $(cd "$RUN_DIR" && git config user.name) <$(cd "$RUN_DIR" && git config user.email)>."

# ── Stage 3: the browser ───────────────────────────────────────────────────
stage "Browser: Chromium for the script-rendered calendars"
say "Registry sources marked fetch: browser are loaded in headless Chromium, which Playwright keeps"
say "in its own cache (~/.cache/ms-playwright), not on the system. The weekly run re-runs this install,"
say "which does nothing unless a Playwright upgrade needs a new Chromium."
(cd "$RUN_DIR" && pnpm exec playwright install --only-shell chromium)
if (cd "$RUN_DIR" && node -e 'import("playwright").then(({ chromium }) => chromium.launch()).then((b) => b.close())' 2>/dev/null); then
  say "Chromium launches."
else
  warn "Chromium is installed but does not launch, most likely for want of system libraries"
  step "Install them with: cd $RUN_DIR && sudo pnpm exec playwright install-deps chromium"
  SKIPPED+=("make Chromium launch: cd $RUN_DIR && sudo pnpm exec playwright install-deps chromium")
fi

# ── Stage 4: keys into the clone's .env ────────────────────────────────────
stage "Keys: the clone's .env"
say "The run reads OPENROUTER_API_KEY and TAVILY_API_KEY from the clone's gitignored .env."
note "Enter keeps the key already in this checkout's $ENV_FILE."
ask_secret OPENROUTER_API_KEY "OpenRouter key:"
ask_secret TAVILY_API_KEY "Tavily key:"
OPENROUTER_API_KEY=$(bare "${OPENROUTER_API_KEY:-}")
TAVILY_API_KEY=$(bare "${TAVILY_API_KEY:-}")
ENV_FILE="$RUN_DIR/.env" # from here on, write_env targets the clone
for key in OPENROUTER_API_KEY TAVILY_API_KEY; do
  if [[ -z "${!key}" ]]; then
    warn "no $key given; every run will fail until it is in $ENV_FILE"
    SKIPPED+=("put $key in $ENV_FILE")
  else
    write_env "$key" "${!key}"
  fi
done

# ── Stage 5: push credential ───────────────────────────────────────────────
stage "Push credential: git uses gh's token"
say "gh auth setup-git makes git use the token gh holds, for every github.com clone of this user."
if confirm "Run gh auth setup-git?"; then
  gh auth setup-git
else
  SKIPPED+=("give git a credential that can push to $REPO (gh auth setup-git, or a deploy key)")
fi
if (cd "$RUN_DIR" && GIT_TERMINAL_PROMPT=0 git push --quiet --dry-run origin main 2>/dev/null); then
  say "A dry-run push from the clone succeeded."
else
  warn "a dry-run push from the clone failed; the weekly run cannot commit until this works"
  SKIPPED+=("fix the push credential: cd $RUN_DIR && git push --dry-run origin main")
fi

# ── Stage 6: the cron line ─────────────────────────────────────────────────
stage "Cron: Mondays at 6:17 a.m. local"
CRON_LINE="$CRON_SCHEDULE PATH=$CRON_PATH $RUN_DIR/scripts/weekly-run.sh"
say "This line goes in your crontab (PATH is set for this job alone; other lines are untouched):"
note "$CRON_LINE"
if confirm "Install it?"; then
  { crontab -l 2>/dev/null | grep -v 'scripts/weekly-run.sh' || true; echo "$CRON_LINE"; } | crontab -
  say "Installed. crontab -l now has:"
  crontab -l | sed 's/^/    /'
else
  SKIPPED+=("add to crontab: $CRON_LINE")
fi

# ── Stage 7: a first run ───────────────────────────────────────────────────
stage "First run"
say "A run started now checks that everything works end to end: it spends real model money (up to"
say "the 5 USD per-run cap) and commits its results to main. It takes a few minutes."
if confirm "Run it now?"; then
  if "$RUN_DIR/scripts/weekly-run.sh"; then
    say "The run passed and pushed. Pull it with: git pull"
  else
    warn "the run failed; it opened an issue with the log's tail, and the full log is under ~/.local/state/kc-this-week/"
    SKIPPED+=("read the failed run's issue and log, fix what it names, then re-run $RUN_DIR/scripts/weekly-run.sh")
  fi
else
  SKIPPED+=("wait for Monday, or run $RUN_DIR/scripts/weekly-run.sh by hand")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
