#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the human steps that switch on the weekly research workflow (#12).
#
# The workflow (.github/workflows/weekly-research.yml) reads two Actions secrets, OPENROUTER_API_KEY
# and TAVILY_API_KEY. This wizard sets both from the keys in the gitignored .env (Enter keeps them),
# then offers to start a first run and watch it. Re-running is safe: secrets are overwritten.
#
#   bash scripts/weekly-workflow-setup.sh
#
# The OpenRouter key's monthly limit, the second spend layer, is set by scripts/hand-run-setup.sh.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
WORKFLOW=weekly-research.yml

banner "KC Events: weekly workflow setup"

# ── Stage 1: GitHub CLI ────────────────────────────────────────────────────
stage "GitHub CLI: signed in to this repo"
say "The secrets are set with the gh CLI, signed in as someone who can administer this repo."
until gh auth status >/dev/null 2>&1; do
  warn "gh is not signed in (or not installed)"
  step "In another terminal, run: gh auth login"
  pause "Press Enter once gh auth status succeeds."
done
REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
say "Secrets will go to ${BOLD}${REPO}${RESET}."
confirm "Is that the right repo?" || { warn "run this from a clone of the right repo"; exit 1; }

# ── Stage 2: OpenRouter key → Actions secret ───────────────────────────────
stage "Actions secret: OPENROUTER_API_KEY"
say "The weekly run pays for model calls with the same OpenRouter key as the hand runs."
note "Enter keeps the key already in $ENV_FILE. To make a new one: https://openrouter.ai/settings/keys"
ask_secret OPENROUTER_API_KEY "OpenRouter key:"
if [[ -z "${OPENROUTER_API_KEY:-}" ]]; then
  warn "no key given; every weekly run will fail until the secret is set"
  SKIPPED+=("GitHub secret OPENROUTER_API_KEY (no key given)")
else
  write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
  set_secret OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
fi

# ── Stage 3: Tavily key → Actions secret ───────────────────────────────────
stage "Actions secret: TAVILY_API_KEY"
say "The discovery lane searches with Tavily; without this key every weekly run fails at the start."
note "Enter keeps the key already in $ENV_FILE. To make a new one: https://app.tavily.com/home"
ask_secret TAVILY_API_KEY "Tavily key:"
if [[ -z "${TAVILY_API_KEY:-}" ]]; then
  warn "no key given; every weekly run will fail until the secret is set"
  SKIPPED+=("GitHub secret TAVILY_API_KEY (no key given)")
else
  write_env TAVILY_API_KEY "$TAVILY_API_KEY"
  set_secret TAVILY_API_KEY "$TAVILY_API_KEY"
fi
say "GitHub now lists these Actions secrets:"
gh secret list 2>/dev/null | sed 's/^/    /' || warn "could not list the secrets"

# ── Stage 4: a first run ───────────────────────────────────────────────────
stage "First run"
say "The schedule fires on Mondays at 11:17 UTC. A run started now checks that everything works:"
say "it spends real model money (up to the 5 USD per-run cap) and commits its results to main."
open_url "https://github.com/${REPO}/actions/workflows/${WORKFLOW}"
if confirm "Start a run now and watch it here?"; then
  gh workflow run "$WORKFLOW" >/dev/null || warn "gh could not start the run; start it from the Actions page"
  note "waiting for GitHub to queue it..."
  RUN_ID=""
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    sleep 3
    RUN_ID=$(gh run list --workflow "$WORKFLOW" --event workflow_dispatch --limit 1 --json databaseId,status \
      --jq '.[] | select(.status != "completed") | .databaseId' 2>/dev/null || true)
    [[ -n "$RUN_ID" ]] && break
  done
  if [[ -z "$RUN_ID" ]]; then
    warn "could not find the run; watch it on the Actions page instead"
    SKIPPED+=("watch the first run on the Actions page")
  elif gh run watch "$RUN_ID" --exit-status; then
    say "The run passed and committed. Pull it with: git pull"
  else
    warn "the run failed; its log is at https://github.com/${REPO}/actions/runs/${RUN_ID}"
    SKIPPED+=("read the failed run's log and fix what it names, then re-run from the Actions page")
  fi
else
  SKIPPED+=("start a first run from the Actions page (Run workflow), or wait for Monday")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
